spring.application.name=giftshop

server.port=8080
spring.datasource.url=jdbc:sqlserver://localhost:1433;databaseName=giftshopdb;encrypt=true;trustServerCertificate=true;

spring.datasource.username=sa
spring.datasource.password=1234
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.SQLServerDialect
logging.level.org.springframework=INFO
logging.level.com.yourpackage=DEBUG

#Jwt properties
app.jwt.secret=daf66e01593f61a15b857cf433aae03a005812b31234e149036bcc8dee755dbb
app.jwt.expiration-ms=604800000

cloudflare.r2.bucket=sba301
cloudflare.r2.accountId=989e644720f9a7f7f4ab87ddef58a5b6
cloudflare.r2.accessKey=89c808ccb60a80a4ec5d59d53ccd9a51
cloudflare.r2.secretKey= ec4b8c5f8b2b604edfd7b36c1ba406cca41463a32bf2e908d75b5eab127046a5
cloudflare.r2.publicUrl=https://pub-44d9cf2d6a344b7293307092b12f7069.r2.dev 